<?php

/**
 * @file
 * News specific functionality for Bene.
 */

use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_form_alter().
 */
function bene_news_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $view_names = ['bene_news'];
  $view = $form_state->getStorage('view');
  if ($form_id == 'views_exposed_form' && in_array($view['view']->id(), $view_names)) {
    $form['date']['min']['#type'] = 'date';
    $form['date']['max']['#type'] = 'date';
  }
}
