<?php

/**
 * @file
 * Core bene code.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_module_implements_alter().
 */
function bene_core_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    case 'form_user_form_alter':
    case 'form_alter':
      bene_core_reorder_indexes($implementations, 'contact', 'bene_core');
      break;

  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Disable the personal contact form config field.
 *
 * @see contact_form_user_form_alter()
 */
function bene_core_form_user_form_alter(&$form, FormStateInterface $form_state) {
  // Disable the user-contact form. Consider basing this on a setting in the
  // future, if this feature is needed.
  $form['contact']['#access'] = FALSE;
}

/**
 * Implements hook_user_format_name_alter().
 */
function bene_core_user_format_name_alter(&$name, $account) {
  // Display the username as the user's email address.
  // Email should always be available, but check first to avoid blank usernames.
  $email = $account->getEmail();
  if (!empty($email)) {
    $name = $email;
  }
}

/**
 * Helper function to re-order hook implementations.
 */
function bene_core_reorder_indexes(&$array, $first, $second) {
  if (isset($array[$second])) {
    $value = $array[$second];
    unset($array[$second]);
    $indexed = array_keys($array);
    $place = array_search($first, $indexed);
    array_splice($indexed, $place + 1, 0, $second);
    $array = array_combine($indexed, array_fill(0, count($indexed), $value));
  }
}

/**
 * Implements hook_user_format_name_alter().
 */
function bene_core_form_block_form_alter(&$form, FormStateInterface $form_state) {
  // The "Bene homepage feature block" is configured to use a
  // "bene_background_image_hero" content block provided by
  // the "block_content" migration.
  // This code sets the appropriate default value for the entity reference field
  // on the block configuration form and prevents the form breaking if the
  // migration has not been run.
  if ($form['id']['#default_value'] == 'benehomepagefeature') {
    // Attempt to load pre-defined "bene_background_image_hero" content block
    // and set as default value for the entity reference field.
    $block = \Drupal::entityTypeManager()->getStorage('block_content')->load($form['settings']['block_id']['#default_value']);

    if (!empty($block)) {
      $form['settings']['block_id']['#default_value'] = $block;
    }
    else {
      // If block does not exist, remove default value from the field.
      $form['settings']['block_id']['#default_value'] = NULL;
    }
  }
}

/**
 * Implements hook_help().
 */
function bene_core_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    case 'entity.menu.edit_form':
      $output .= '<ul>';
      $output .= '<li>' . t('Here you can edit an existing main navigation link or add a new one.') . '</li>';
      $output .= '<li>' . t('You can organize how your navigation will appear by dragging and dropping each menu link up or down. The top listed menu link will be the farthest left on your screen.') . '</li>';
      if ($route_match->getRawParameter('menu') == 'main') {
        $output .= '<li>' . t('The last listed menu link will automatically appear as a button - the suggestion is to put “support us” or “donate” here.') . '</li>';
      }
      $output .= '</ul>';

  }
  return $output;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bene_core_form_entity_embed_dialog_alter(&$form, FormStateInterface $form_state) {
  if ($form_state->getStorage()['entity']) {
    if ($form_state->getStorage()['entity']->bundle() != 'image') {
      $form['attributes']['data-align']['#access'] = FALSE;
    };
  }
}

/**
 * Implements hook_entity_embed_alter().
 */
function bene_core_entity_embed_alter(array &$build, EntityInterface $entity, array &$context) {
  $type = $build['#entity']->bundle();
  $build['#attributes']['class'][] = $type;
}
