<?php

/**
 * @file
 * Core bene code.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_module_implements_alter().
 */
function bene_core_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    case 'form_user_form_alter':
    case 'form_alter':
      bene_core_reorder_indexes($implementations, 'contact', 'bene_core');
      break;

  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Disable the personal contact form config field.
 *
 * @see contact_form_user_form_alter()
 */
function bene_core_form_user_form_alter(&$form, FormStateInterface $form_state) {
  // Disable the user-contact form. Consider basing this on a setting in the
  // future, if this feature is needed.
  $form['contact']['#access'] = FALSE;
}

/**
 * Implements hook_user_format_name_alter().
 */
function bene_core_user_format_name_alter(&$name, $account) {
  // Display the username as the user's email address.
  // Email should always be available, but check first to avoid blank usernames.
  $email = $account->getEmail();
  if (!empty($email)) {
    $name = $email;
  }
}

/**
 * Helper function to re-order hook implementations.
 */
function bene_core_reorder_indexes(&$array, $first, $second) {
  if (isset($array[$second])) {
    $value = $array[$second];
    unset($array[$second]);
    $indexed = array_keys($array);
    $place = array_search($first, $indexed);
    array_splice($indexed, $place + 1, 0, $second);
    $array = array_combine($indexed, array_fill(0, count($indexed), $value));
  }
}

/**
 * Implements hook_user_format_name_alter().
 */
function bene_core_form_block_form_alter(&$form, FormStateInterface $form_state) {
  // The "Bene homepage feature block" is configured to use a
  // "bene_background_image_hero" content block provided by
  // the "block_content" migration.
  // This code sets the appropriate default value for the entity reference field
  // on the block configuration form and prevents the form breaking if the
  // migration has not been run.
  if ($form['id']['#default_value'] == 'benehomepagefeature') {
    // Attempt to load pre-defined "bene_background_image_hero" content block
    // and set as default value for the entity reference field.
    $block = \Drupal::entityTypeManager()->getStorage('block_content')->load($form['settings']['block_id']['#default_value']);

    if (!empty($block)) {
      $form['settings']['block_id']['#default_value'] = $block;
    }
    else {
      // If block does not exist, remove default value from the field.
      $form['settings']['block_id']['#default_value'] = NULL;
    }
  }
}
