<?php

/**
 * @file
 * Support for instagram posts as media entities in Bene.
 */

use Drupal\bene_core\OverrideHelper as Override;
use Drupal\bene_media_instagram\Plugin\MediaEntity\Type\Instagram;

/**
 * Implements hook_media_entity_type_info_alter().
 */
function bene_media_instagram_media_entity_type_info_alter(array &$types) {
  $types['instagram']['input_match'] = [
    'constraint' => 'InstagramEmbedCode',
    'field_types' => [
      'string',
      'string_long',
    ],
  ];
  $types['instagram']['preview'] = TRUE;

  Override::pluginClass($types['instagram'], Instagram::class);
}
