desc 'Install dependencies'
task :install do
  system 'bundle install'
  system 'npm install -g browser-sync'
  system 'npm install -g watchify'
  system 'npm install -g uglify-js'
  system 'npm install webpack --save'
  system 'npm install babel-loader babel-preset-es2015 --save'
end

# Change basetheme.dev to your site path
desc 'Running Browsersync'
task :browsersync do
  system 'browser-sync start --proxy "benefit.dev" --files "css/*.css" --no-inject-changes'
end

desc 'Watch sass'
task :sasswatch do
  system 'sass -r sass-globbing --watch sass/benefit.scss:css/benefit.css'
end

desc 'Build JS'
task :webpack do
  system './node_modules/.bin/webpack -w ./js/main.js ./js/main-dist.js'
end

desc 'Serve'
task :serve do
  threads = []
  %w{sasswatch webpack browsersync}.each do |task|
    threads << Thread.new(task) do |devtask|
      Rake::Task[devtask].invoke
    end
  end
  threads.each {|thread| thread.join}
  puts threads
end
